---
# General
- name: Update RedHat system
  block:
    - name: Update system
      dnf:
        name: "*"
        state: latest
  when: ansible_os_family == "RedHat"

- name: Populate service facts
  service_facts:

- name: Install jenkins
  import_tasks: jenkins.yaml

- name: Install gitea
  import_tasks: gitea.yaml
